title: "Rancilio-PID Handbook"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true
logo: http://rancilio-pid.de/wp-content/uploads/2018/08/SmallLogo-e1535533340407.png
# Aux links for the upper right navigation
aux_links:
  "Rancilio-PID Handbook on GitHub":
    - "//github.com/rasimriver/ranciliopid-handbook"
  "Rancilio-PID Website":
    - "http://rancilio-pid.de/"
warnhinweis: Das Arbeiten mit 230 V kann tödlich sein! **Bitte trennt eure Maschine vollständig vom Stromnetz bevor ihr irgendeine Schraube löst oder das Gehäuse öffnet!** Es reicht nicht einen Schalter an der Maschine oder Steckdose zu betätigen, wenn ihr an der Maschine arbeitet wollt. Auch smarte Steckdosen trennen nicht vollständig vom Netz, selbst wenn sie ausgeschaltet sind! **Der Netzstecker muss immer gezogen werden!** Ihr handelt auf eigene Gefahr und seid selbst für den Umbau verantwortlich.
