title: "Rancilio-PID Handbook"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true
logo: http://rancilio-pid.de/wp-content/uploads/2018/08/SmallLogo-e1535533340407.png
# Aux links for the upper right navigation
aux_links:
  "Rancilio-PID Handbook on GitHub":
    - "//github.com/rasimriver/ranciliopid-handbook"
  "Rancilio-PID Website":
    - "http://rancilio-pid.de/"
warnhinweis: Das Arbeiten mit 230 V kann tödlich sein! Die Anleitungen auf der Webseite soll euch einen Eindruck geben, wie ihr selbst einen PID Regler in eine Rancilio Silvia oder ähnliche Espressomaschinen einbauen könnt. Bei Arbeiten mit 230 V immer den Netzstecker ziehen. Ihr handelt dabei auf eigene Gefahr.
